### ISSUE TITLE
Softlocks when I try to edit specific parts of a skill

### ISSUE THREAD

**Issue by 06ninjajack** [LazyBone152/XenoKit#18]
System.ArgumentNullException: Object cannot be null.
Parameter name: source
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(Exception source)
   at XenoKit.Editor.Files.<Initialize>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XenoKit.Editor.Files.<Initialize>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by 06ninjajack** [comment]
Figured this would have something to do with what I'm trying to fix.
