### ISSUE TITLE
Relative paths in BCS not supported

### ISSUE THREAD

**Issue by Atsuraelu** [LazyBone152/XenoKit#2]
The BCS files element supports loading from different directories via relative paths, i.e. `<Files EMD="../OtherDir/File" EMM="" EMB="" EAN="" />`. The game would load chara/OtherDir/File.emd in this case.
XenoKit does not support this and tries to load the file from the characters base directory, so chara/HUF/File.emd for example.

**Comment by LazyBone152** [comment]
Is this still a issue in 0.1.2?

**Comment by Atsuraelu** [comment]
While we talked on Discord a while ago, I'll also post it here for completeness sake:

While above given example works now (for example loading `../VDL/VDL_005_Hair` from HUF.bcs loads fine), loading stuff like `../CCCE/HUF/HUF_kumabound_Freckles2` still gives the following error in 0.1.4:

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: The file "chara/HUF/HUF_kumabound_freckles_000.emd" does not exist in the game directory or cpks.
   at Xv2CoreLib.FileManager.GetParsedFileFromGame(String path, Boolean onlyFromCpk, Boolean raiseEx, Boolean forceReload) in C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\FileManager.cs:line 173
   at Xv2CoreLib.Xv2PartSetFile.Load(Boolean allowReload) in C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\Xv2Character.cs:line 651
   at Xv2CoreLib.Xv2Character.GetPartSetFile(String name) in C:\source\XenoverseTools\XV2 Tools\Xv2CoreLib\Xenoverse2\Xv2Character.cs:line 367
   at XenoKit.Engine.CharaPart.GetFilePath(String path, String pathOnParent)
   at XenoKit.Engine.CharaPart.LoadEmd()
   at XenoKit.Engine.CharaPart.LoadSources()
   at XenoKit.Engine.CharaPart.LoadPart()
   at XenoKit.Engine.CharaPart..ctor(GameBase gameBase, Actor chara, Part part, PartType type)
   at XenoKit.Engine.CharaPartSet.ApplyTransformation(Int32 index)
   at XenoKit.Views.BcsPartSetView.ApplyTransformation()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at GalaSoft.MvvmLight.Helpers.WeakAction.Execute() in C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Helpers\WeakAction.cs:line 357
   at GalaSoft.MvvmLight.CommandWpf.RelayCommand.Execute(Object parameter) in C:\Users\lbugn\Documents\MVVMLight\GalaSoft.MvvmLight\GalaSoft.MvvmLight (PCL)\Command\RelayCommand.cs:line 230
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by LazyBone152** [comment]
This should actually be fixed now but I haven't updated the code on GitHub yet.

I'm currently in the middle of a fairly big update and things aren't entirely stable enough right now. So not sure when an update will happen.

**Comment by Atsuraelu** [comment]
Works in 0.2.
Thank you!
